apiVersion: v1
kind: Pod
metadata:
  name: inflate
spec:
  containers:
  - name: inflate
    image: nginx
    resources:
      requests:
        cpu: "4"
        memory: "2Gi"
    ports:
    - containerPort: 80
  nodeSelector:
    karpenter.sh/provisioner-name: default
