apiVersion: apps/v1
kind: Deployment
metadata:
  name: stream
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stream
  template:
    metadata:
      labels:
        app: stream
        istio-injection: enabled
    spec:
      containers:
        - name: stream
          image: 745173969277.dkr.ecr.ap-northeast-2.amazonaws.com/daenamu:stream
          imagePullPolicy: Always
          ports:
            - containerPort: 8003
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: stream-secret
                  key: DB_HOST
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: stream-secret
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: stream-secret
                  key: DB_PASSWORD
            - name: aws.s3.access-key
              valueFrom:
                secretKeyRef:
                  name: stream-secret
                  key: aws.s3.access-key
            - name: aws.s3.secret-key
              valueFrom:
                secretKeyRef:
                  name: stream-secret
                  key: aws.s3.secret-key
            - name: aws.s3.session-token
              valueFrom:
                secretKeyRef:
                  name: stream-secret
                  key: aws.s3.session-token
            - name: S3_BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: stream-secret
                  key: S3_BUCKET_NAME
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: stream
  namespace: default
spec:
  selector:
    app: stream
  ports:
    - port: 8003
      targetPort: 8003
  type: ClusterIP
