name: Terraform + Helm Deploy with Steps

on:
  push:
    branches: [main]

env:
  AWS_REGION: ap-northeast-2
  CLUSTER_NAME: daenamu-test

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.12.1

      # provider 충돌 방지: Kubernetes/Helm provider 제거
      - name: Temporarily disable kube_providers.tf
        run: |
          mkdir -p skipped
          mv kube_providers.tf skipped/ || true

      - name: Terraform Init
        run: terraform init

      # 복원 후 Helm, Kubernetes 리소스 문제 없이 처리
      - name: Restore kube_providers.tf
        run: |
          mv skipped/kube_providers.tf . || true

      - name: Import IAM resources
        env:
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
        run: |
          # EKS 클러스터용 IAM 역할
          terraform import aws_iam_role.cluster daenamu-test-eks-cluster-role || true
          terraform import aws_iam_role_policy_attachment.cluster_AmazonEKSClusterPolicy arn:aws:iam::${AWS_ACCOUNT_ID}:role/daenamu-test-eks-cluster-role/arn:aws:iam::aws:policy/AmazonEKSClusterPolicy || true
          terraform import aws_iam_role_policy_attachment.cluster_AmazonEKSVPCResourceController arn:aws:iam::${AWS_ACCOUNT_ID}:role/daenamu-test-eks-cluster-role/arn:aws:iam::aws:policy/AmazonEKSVPCResourceController || true

          # Fargate Pod Execution Role
          terraform import aws_iam_role.pod_execution daenamu-test-eks-pod-execution-role || true
          terraform import aws_iam_role_policy_attachment.pod_execution_AmazonEKSFargatePodExecutionRolePolicy arn:aws:iam::${AWS_ACCOUNT_ID}:role/daenamu-test-eks-pod-execution-role/arn:aws:iam::aws:policy/AmazonEKSFargatePodExecutionRolePolicy || true

          # EC2 Node Group Role
          terraform import aws_iam_role.node_group daenamu-test-node-group-role || true
          terraform import aws_iam_instance_profile.node_group daenamu-test-node-group-instance-profile || true
          terraform import aws_iam_role_policy_attachment.AmazonEKSWorkerNodePolicy arn:aws:iam::${AWS_ACCOUNT_ID}:role/daenamu-test-node-group-role/arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy || true
          terraform import aws_iam_role_policy_attachment.AmazonEKS_CNI_Policy arn:aws:iam::${AWS_ACCOUNT_ID}:role/daenamu-test-node-group-role/arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy || true
          terraform import aws_iam_role_policy_attachment.AmazonEC2ContainerRegistryReadOnly arn:aws:iam::${AWS_ACCOUNT_ID}:role/daenamu-test-node-group-role/arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly || true

          # ALB Controller
          terraform import aws_iam_role.alb_sa_role AmazonEKSLoadBalancerControllerRole || true
          terraform import aws_iam_policy.alb_policy arn:aws:iam::${AWS_ACCOUNT_ID}:policy/AWSLoadBalancerControllerIAMPolicy || true
          terraform import aws_iam_role_policy_attachment.alb_policy_attach arn:aws:iam::${AWS_ACCOUNT_ID}:role/AmazonEKSLoadBalancerControllerRole/arn:aws:iam::${AWS_ACCOUNT_ID}:policy/AWSLoadBalancerControllerIAMPolicy || true

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Create steps.sh dynamically with loop
        run: |
          echo '#!/bin/bash' > steps.sh
          echo 'set -e' >> steps.sh
          for i in {1..10}; do
            echo "./step${i}.sh" >> steps.sh
          done
          chmod +x steps.sh

      - name: Run Steps
        run: ./steps.sh

      - name: Update Kubeconfig for EKS
        run: |
          aws eks update-kubeconfig \
            --name ${{ env.CLUSTER_NAME }} \
            --region ${{ env.AWS_REGION }}

      # - name: Install Helm
      #   run: |
      #     curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

