name: Destroy EKS + Helm Infra

on:
  workflow_dispatch:

env:
  AWS_REGION: ap-northeast-2
  CLUSTER_NAME: daenamu-test

jobs:
  destroy:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.12.1

      - name: Terraform Init
        run: terraform init

      - name: Update Kubeconfig for EKS
        run: |
          aws eks update-kubeconfig \
            --name ${{ env.CLUSTER_NAME }} \
            --region ${{ env.AWS_REGION }}

      - name: Create stepxs.sh dynamically with loop
        run: |
          echo '#!/bin/bash' > stepxs.sh
          echo 'set -e' >> stepxs.sh
          for i in 10 7 6 9 5 4 3 2 1; do
            echo "./step${i}x.sh" >> stepxs.sh
          done
          chmod +x stepxs.sh

      - name: Make destroy scripts executable
        run: chmod +x ./step*x.sh

      - name: Run destroy steps
        run: ./stepxs.sh
